# 회원 가입
POST {{user-service}}/user
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "password",
  "name": "choi-ys"
}
> {%
client.global.set("signupUserId", response.body.userId)
%}

###

# 로그인
POST {{user-service}}/login
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "password"
}

> {%
client.global.set("accessToken", response.headers.valueOf("token"))
%}

###

# 특정 회원 조회
GET {{user-service}}/user/{{signupUserId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###

# 회원 목록 조회
GET {{user-service}}/user?page=0&size=10&sort=createdAt&direction=DESC
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###