server:
  port: 0 # 동일 Application의 다중 인스턴스 구동을 위한 Random port 설정

spring:
  application:
    name: user-service

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  jpa:
    hibernate:
      ddl-auto: create-drop

  # add p6syp-configurations bean to sleuth-zipkin
  main:
    allow-bean-definition-overriding: true
---
logging:
  level:
    io.ecommerce.userservice.core.client: debug

---
ip-address:
  gateway: 192.168.1.57
