server:
  port: 0 # 동일 Application의 다중 인스턴스 구동을 위한 Random port 설정

spring:
  application:
    name: product-service

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
