server:
  port: 0 # 동일 Application의 다중 인스턴스 구동을 위한 Random port 설정

spring:
  application:
    name: product-service

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  jpa:
    hibernate:
      ddl-auto: create-drop

  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: product-service

  # add p6syp-configurations bean to sleuth-zipkin
  main:
    allow-bean-definition-overriding: true
